version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sv-kassa-db
    ports:
      - "6543:5432"  
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
